# Generated by Django 4.1.7 on 2023-04-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='payment_status',
    #         old_name='product_id',
    #         new_name='cart_id',
    #     ),
    # ]
