# Generated by Django 4.1.7 on 2023-03-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_model", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book_details", old_name="book_id", new_name="product_id",
        ),
    ]
