# Generated by Django 4.1.7 on 2023-03-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
