# Generated by Django 4.1.7 on 2023-03-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=10)),
                ('feedback', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=5)),
            ],
        ),
    ]
